# Generated by Django 3.2 on 2022-07-15 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220716_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 21, 9, 51, 538541, tzinfo=utc)),
        ),
    ]
